---
title: "Untitled"
author: "Vaishali"
date: "`r Sys.Date()`"
output: html_document
---


knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(knitr)
library(lubridate)
setwd("C:/Users/VWaghmare/Git/C113/LabRecon")
#getwd()
library(haven)
install.packages("Hmisc")
library("Hmisc")
install.packages(c("openxlsx", "labelled"))
library(openxlsx)
library(labelled)


sample<- read_sas("C:/Users/VWaghmare/Git/C113/Data/sample.sas7bdat")
#View(sample)
dt <- sample %>% select(SUBJID, SPSTAT, VISIT, VISITNUM, SPDTTM) %>% filter(SPSTAT == '1') %>% mutate(SAMPLE_COL_DATE = as_date(dmy_hm(SPDTTM))) %>% mutate(Merge_Dt = as_date(dmy_hm(SPDTTM))) %>% mutate(VISNUM = case_when(
  VISITNUM =="D1" ~ "V2",
  VISITNUM =="D3" ~ "V3",
  VISITNUM =="D8" ~ "V4",
  TRUE ~ " "
)) %>% mutate(edc_sub = SUBJID)
#View(dt)

lab_dt<- read_csv("C:/Users/VWaghmare/Git/C113/LabRecon/lab_data_11Mar2025.csv")
#View(lab_dt)
lab <- lab_dt %>% mutate(VISNUM = Visit) %>% mutate(SUBJID = `Subject ID`) %>% mutate(Lab_Draw_date = as.Date(`Date Drawn`, format = "%m/%d/%Y")) %>%  mutate(Merge_Dt = as.Date(`Date Drawn`, format = "%m/%d/%Y"))
#View(lab)

#merge lab data and EDC data

vislab<- full_join(dt, lab, by =c("SUBJID", "VISNUM"))
#View(vislab)



vislab_c <- vislab %>% mutate(flag = case_when(
    is.na(edc_sub) ~ 'Not in EDC',
    is.na(`Subject ID`)~ 'Not in Lab',
    TRUE ~ " "
)
)
View(vislab_c)

vislab_cc <- vislab_c %>% mutate(flag = case_when(
    flag == " " & SAMPLE_COL_DATE != Lab_Draw_date ~ "Date Mismatch",
    TRUE ~ flag
    
))
#View(vislab_cc)




final <- vislab_cc  %>%  select(SUBJID, VISIT, VISNUM, `Material Type`, `Material Modifiers`, SAMPLE_COL_DATE, Lab_Draw_date, flag ) 
#View(final)



my_labels <- c(SUBJID = 'Subject ID',
               VISIT = 'Visit in EDC',
               VISNUM = 'Visit Number',
               `Material Type` = 'Material Type',
               `Material Modifiers` = 'Material Modifiers',
               SAMPLE_COL_DATE = 'Sample Collection Date',
               Lab_Draw_date = 'Lab Draw Date',
               flag = 'Flag')


final_ <- final
#View(final_)
label(final_) <-as.list(my_labels[match(names(final_), names(my_labels))])
#View(final_)
final_c <- final_ %>% filter(flag != " ")
#View(final_c)

get_var_labels <- function(data) {
  sapply(data, var_label)
}

# Get variable labels
var_labels <- get_var_labels(final_c)

# Create a copy of the data frame
final_with_labels <- final_c

# Replace column names with variable labels
colnames(final_with_labels) <- unname(var_labels)

#get today's date
today <- Sys.Date()
tdt <- format(today, "%Y-%m-%d")
# Create the filename
filename <- paste0("C113_Lab_recon_", tdt, ".xlsx")

# Create a workbook
wb <- createWorkbook()

# Add a sheet with a specific name 
addWorksheet(wb, sheetName = "Lab Recon")

# Write the data to the sheet
writeData(wb, sheet = "Lab Recon", x = final_with_labels)

# Save the workbook
saveWorkbook(wb, file = filename,overwrite = TRUE)


#write.xlsx(final_c, file = "C:/Users/VWaghmare/Git/C113/LabRecon/output/lab_recon.xlsx")








